### ISSUE TITLE
So i merged your Armor Stands Fix

### ISSUE THREAD

**Issue by dexslab** [Camotoy/Geyser#13]
So i merged your armor stands fix to attempt to get MiniaturePets working but of course there are still some issues. What i can say is that for the most part its working just need to figure out what to do to get the proper models to load. 
![mpets-panda](https://user-images.githubusercontent.com/1696130/99617669-c9872f80-29ed-11eb-93f0-3c59cc924ad8.png)
![mpets-mp8](https://user-images.githubusercontent.com/1696130/99617672-ca1fc600-29ed-11eb-80d8-1d5e9e176d20.png)

**Comment by Camotoy** [comment]
Player heads are going to be their own issue - they don't exist in Bedrock. So more workarounds will be needed there.

**Comment by dexslab** [comment]
Well i was working on the Custom Skulls that was implemented but i think it only applies to blocks

**Comment by Camotoy** [comment]
Closing as armor stand fixes are now merged.
