### ISSUE TITLE
Please update non-full-chunk branch to 1.16

### ISSUE THREAD

**Issue by MasterLuke117** [Camotoy/Geyser#9]
i have a geyser plus spigot FAWE enabled creative server ive been using the non-full-chunk branch to temp fix the
issues with FAWE, 

please update this branch to 1.16.

Thanks!!

Luke

**Comment by Camotoy** [comment]
Sorry I never got a notification for this! Regardless, the branch is now merged into Geyser master.

**Comment by MasterLuke117** [comment]
Thank you for merging it into master.
